### PR TITLE
DEVX-2292: Updates default versions in Makefile for docker building

### PR DESCRIPTION
**Pull request by rspurgeon**
This updates documentation and the Makefile with default values for 6.0.1 CP

##### Testing done:
- [ ] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

## Release Plan
This does not build any new Connector jar, only updates defaults for documentation and the Makefile used to release DevX images for demos/examples.

### CODE REVIEW

**Review by ybyzek — COMMENTED** [review]
@rspurgeon 

1. I have not validated this but assume you have? (to make sure no weird Avro dependency problems like in earlier releases -- unlikely in a `.1` but possible)

2. I defer to you (and maybe guidance from @C0urante ), but is `master` the right target branch or would it possibly be better suited for `0.4.x`?

**Comment by rspurgeon** [comment]
@ybyzek retargeted 0.4.x 
cc @awalther28

**Comment by rspurgeon** [comment]
> @rspurgeon
> 
>     1. I have not validated this but assume you have? (to make sure no weird Avro dependency problems like in earlier releases -- unlikely in a `.1` but possible)

@ybyzek this particular change was only to update the default variables in the makefile and readme.  The actual image was that pairs together the already existing built artficats was built and pushed.  I'm validating in demos that use it elsewhere (https://github.com/confluentinc/cp-all-in-one/pull/52)

**Comment by rspurgeon** [comment]
Some validation:

`
➜ docker ps | grep cp-server-connect-datagen
fc8e636e2efc        cnfldemos/cp-server-connect-datagen:0.4.0-6.0.1   "/etc/confluent/dock…"   9 minutes ago       Up 9 minutes        0.0.0.0:8083->8083/tcp, 9092/tcp                 connect

[I] ➜ curl -XGET :8083/connectors/datagen-pageviews/status | jq
{
  "name": "datagen-pageviews",
  "connector": {
    "state": "RUNNING",
    "worker_id": "connect:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "RUNNING",
      "worker_id": "connect:8083"
    }
  ],
  "type": "source"
}
`

**Pull request merged**
