### PR TITLE
Use schema of schema.keyfield instead of String

### PR DESCRIPTION
**Pull request by ryan-carlson**

### CODE REVIEW

**Comment by C0urante** [comment]
Hi @ryan-carlson! I believe we've already implemented this feature in https://github.com/confluentinc/kafka-connect-datagen/pull/51, which allows for both null and non-string keys. It's been merged to our 0.3.x branch, and we're planning on putting out an 0.3.0 release of the connector shortly that should include that functionality.

Let us know if those changes look acceptable to you; if so, we can close this PR. Otherwise, happy to discuss any requirements you may have that aren't covered by the connector yet.

**Comment by C0urante** [comment]
Update: we've published the [0.3.0 release](https://github.com/confluentinc/kafka-connect-datagen/releases/tag/v0.3.0) and it should be available [on Confluent Hub](https://www.confluent.io/hub/confluentinc/kafka-connect-datagen) shortly.

**Comment by ryan-carlson** [comment]
@C0urante Great news!!  I will be checking this out today!

**Comment by ryan-carlson** [comment]
@C0urante Thanks again!  I tested this out today with the new version and everything is working as expected!
👍

**Pull request closed without merging**
