### PR TITLE
[DO NOT MERGE] CC-7063: Bump CP parent version, upgrade to Avro 1.9.1

### PR DESCRIPTION
**Pull request by C0urante**
[Jira](https://confluentinc.atlassian.net/browse/CC-7063)

This shouldn't be merged until CP 5.4 is released, as well as version 2.4 of the Avro Random Generator.

### CODE REVIEW

**Comment by ybyzek** [comment]
@C0urante thanks for the proactive attention on this issue!

Questions:

# Should this be targetted to `0.1.x` instead of `master?
# I'm concerned about the timing.  If this is waiting for 5.4 to be released, then that means there will be a period of time when the CP quickstart won't work when 5.4 is released, right?  Because we still need to build a new release of the connector that works just with 5.4

**Comment by C0urante** [comment]
@ybyzek I think merging against `master` is safer since the changes here will bump a bunch of dependency versions that may have unintended consequences for pre-CP 5.4 Connect clusters running this connector. If the changes here make the connector non-viable on those clusters, then it may behoove us to retain an untouched branch that we can still make other bug fixes against so those users aren't hung out to dry. Additionally, I'd argue that the changes here aren't strictly a bug fix and so aren't really applicable for targeting an existing feature branch.

As far as the period between the CP 5.4 release and the release of this connector goes--the release job for this connector is very fast; the biggest factor for the length of that period would be how quickly we choose to perform the release after CP 5.4 comes out.

**Comment by ybyzek** [comment]
@C0urante -- 

wrt branch/versioning: would love to solicit advice from @rhauch on this issue.

wrt 5.4 release timing: there are other tasks that must be done.  Once there is a new kafka-connect-datagen set of jars available on Confluent Hub (which is what you are referring to), the additional tasks include publishing custom Docker images used by the CP quickstart and other DevX examples.  

Concern 1: I'm not saying that this process isn't fast, but I'm saying there are a lot of pieces that need to fall into place, even after the kafka-connect-datagen is rev'd.

Concern 2: we can't validate the CP quickstart nor those demos until this image is built, and it is unacceptable to wait until 5.4 GA to do that validation.  We need to be able to validate before 5.4 GA.

So we really need to find a way to publish this early to ensure all the bits are available and to validate all the quickstarts and demos.

**Comment by sonupillai** [comment]
@C0urante Do we have a resolution here? Is this the approach we took in the past when this happened? I am wondering that even if we update this connector on the hub today, shouldn't it be backward compatible with the older versions of CP?

**Pull request closed without merging**
